export default {
  NODE_LIST: 'NODE_LIST',
  NODE_CREATED: 'NODE_CREATED',
  NODE_UPDATED: 'NODE_UPDATED',
  NODE_DELETED: 'NODE_DELETED',
  LINK_LIST: 'LINK_LIST',
  LINK_CREATED: 'LINK_CREATED',
  LINK_DELETED: 'LINK_DELETED'
}
